title: Your title


#optional
customHeader: Katz #if you want the header text to be different than your site title
subheader: Life is not a problem to be solved, but a reality to be experienced

links:
    - url: https://google.com/
      name: Google
    - url: https://github.com/mykatz
      name: Github
    - url: https://google.com/
      name: Google
    - url: https://github.com/mykatz
      name: Github
    - url: https://google.com/
      name: Google
    - url: https://github.com/mykatz
      name: Github
sass:
    sass_dir: _sass
    style: compressed