title: Your title


#optional
customHeader: Katz #if you want the header text to be different than your site title
subheader: Life is not a problem to be solved, but a reality to be experienced

links:
    - url: https://github.com/mykatz
      name: Github
    - url: https://linkedin.com/mykatz
      name: LinkedIn
    - url: https://k4tz.xyz/resume
      name: Resume
    - url: https://medium.com/@k4tz
      name: Medium


sass:
    sass_dir: _sass
    style: compressed